version: "2"

services:
  zookeeper-server:
    image: 'bitnami/zookeeper:latest'
    networks:
      - kafkanet
    ports:
      - 2181:2181
    environment: 
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafkaserver:
    image: "bitnami/kafka:latest"
    container_name: kafka
    hostname: kafkaserver
    networks:
      - kafkanet
    ports:
      - 9092:9092
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper-server
  kafka_manager:
    image: "hlebalbau/kafka-manager:stable"
    container_name: kafkamanager
    networks:
      - kafkanet
    ports:
      - 9000:9000
    # links:
    #   - zookeeper-server
    environment:
      ZK_HOSTS: "zookeeper-server:2181"
    depends_on: 
      - zookeeper-server
    command:
      -Dpidfile.path=/dev/null

networks:
  kafkanet:
    driver: bridge